name: Github CI

on:
  schedule:
      - cron:  '0 23 28 * *'
  push:
    branches:
      - 'main'

jobs:
    build:
      runs-on: ubuntu-latest
      steps:

        - name: Check Out Repo 
          uses: actions/checkout@v3

        - name: Login to DockerHub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKERHUB_USER }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

        - name: Set up Docker Buildx
          id: buildx
          uses: docker/setup-buildx-action@v2

        - name: Build and push base image
          id: docker_build_base
          uses: docker/build-push-action@v4
          with:
            context: ./
            file: ./base.dockerfile
            push: true
            tags: ejtrader/pytorch-notebook:base, ejtrader/pytorch-notebook 

        - name: Build and push devel image
          id: docker_build_devel
          uses: docker/build-push-action@v4
          with:
            context: ./
            file: ./base-devel.dockerfile
            push: true
            tags: ejtrader/pytorch-notebook:devel

        - name: Image digest
          run: |
            echo ${{ steps.docker_build_base.outputs.digest }}
            echo ${{ steps.docker_build_devel.outputs.digest }}
